{{- if and .Values.objectStorage.enabled (not .Values.objectStorage.reuseClusterFromNamespace) -}}
{{- $rgwSecretSpec := (merge (dict "name" "rgw-secret") .) -}}
{{- $rgwSecret := include "udh.secret" $rgwSecretSpec }}
{{ include "udh.secretManifest" (merge (dict "value" $rgwSecret) $rgwSecretSpec) }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ printf "%s-rook-ceph-cluster" (include "common.names.fullname" .) | quote }}
spec:
  releaseName: {{ include "data-hub.name" (dict "context" . "name" "rook-ceph-cluster") }}
  timeout: 20m
  targetNamespace: {{ .Release.Namespace }}
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.19.5 # renovate: datasource=helm depName=rook-ceph-cluster versioning=helm registryUrl=https://charts.rook.io/release
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: {{ printf "%s-rook" (include "common.names.fullname" .) | quote }}
  interval: 1h0m0s
  {{- if .Values.objectStorage.operator.enabled }}
  dependsOn:
    - name: {{ printf "%s-rook-ceph" (include "common.names.fullname" .) | quote }}
  {{- end }}
  values:
    {{- if .Values.objectStorage.operator.enabled }}
    operatorNamespace: {{ .Release.Namespace }}
    {{- end }}
    cephClusterSpec:
      {{- if .Values.objectStorage.allowDeletion }}
      cleanupPolicy:
        confirmation: yes-really-destroy-data
      {{- end }}
      dataDirHostPath: /var/lib/rook/ns/{{ .Release.Namespace }}
      removeOSDsIfOutAndSafeToRemove: true
      cephConfig:
        global:
          osd_pool_default_size: "1"
          mon_warn_on_pool_no_redundancy: "false"
          rgw_sts_key: {{ $rgwSecret | quote }}
          rgw_s3_auth_use_sts: "true"
      mon:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: {{ .Values.objectStorage.monStorage }}
        {{- if .Values.objectStorage.singleNode }}
        count: 1
        {{- end }}
      mgr:
        count: 1
        modules:
          - name: rook
            enabled: true
      storage:
        useAllDevices: false
        storageClassDeviceSets:
          - name: set1
            count: 1
            portable: true
            tuneDeviceClass: true
            tuneFastDeviceClass: false
            encrypted: false
            placement:
              topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: kubernetes.io/hostname
                  whenUnsatisfiable: ScheduleAnyway
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd
            preparePlacement:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                          - key: app
                            operator: In
                            values:
                              - rook-ceph-osd
                          - key: app
                            operator: In
                            values:
                              - rook-ceph-osd-prepare
                      topologyKey: kubernetes.io/hostname
              topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: kubernetes.io/hostname
                  whenUnsatisfiable: DoNotSchedule
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - rook-ceph-osd-prepare
            volumeClaimTemplates:
              - metadata:
                  name: data
                spec:
                  resources:
                    requests:
                      storage: {{ .Values.objectStorage.storage }}
                  volumeMode: Block
                  accessModes:
                    - ReadWriteOnce
        onlyApplyOSDPlacement: false
      {{- if .Values.global.testDeployment }}
      resources:
        mgr:
          requests:
            cpu: "20m"
        mon:
          requests:
            cpu: "20m"
        osd:
          requests:
            cpu: "20m"
            memory: "1Gi"
        prepareosd:
          requests:
            cpu: "20m"
        mgr-sidecar:
          requests:
            cpu: "20m"
        crashcollector:
          requests:
            cpu: "20m"
        logcollector:
          requests:
            cpu: "20m"
        cleanup:
          requests:
            cpu: "20m"
        exporter:
          requests:
            cpu: "20m"
      {{- end }}
    toolbox:
      enabled: true
      {{- if .Values.global.testDeployment }}
      resources:
        requests:
          cpu: "20m"
      {{- end }}
    dashboard:
      enabled: false
    cephBlockPools: []
    cephFileSystems: []
    cephObjectStores:
      - name: bucket
        spec: {{- include "udh.objectstore.spec" . | nindent 10 }}
        storageClass:
          enabled: false
        ingress:
          enabled: true
          annotations:
            {{- include "udh.objectstore.ingress.annotations" . | nindent 12 }}
          host:
            name: {{ include "data-hub.storage.hostname" . }}
            path: /
          tls:
          - hosts:
              - {{ include "data-hub.storage.hostname" . }}
            secretName: {{ include "data-hub.storage.hostname" . }}-tls
{{- end -}}
