apiVersion: v2
name: udh-platform
description: teuto.net urban data components
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: common
    version: 2.13.3
    repository: https://charts.bitnami.com/bitnami