global:
  baseDomain: data-hub.local
  udhImageRegistry: "localimage.test"
  auth:
    issuer: https://login.data-hub.local/realms/udh
  smtp_base_domain: udh-platform@teuto.net
  storageClass: standard
  sslInsecureSkipVerify: true
  ingress:
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issuer: "udh-test-iss"
grafana:
  smtp:
    enabled: true
    from_adress: alert@example.com
    from_name: grafana-local
    user: ""
    password: ""
keycloak:
  debug: true
  logLevel: info,udh:debug
  extensions:
    image:
      registry: "localimage.test"
      pullPolicy: IfNotPresent
      repository: "keycloak-extensions"
      tag: ""
      digest: ""
  testUsers:
    data-hub-admin:
      username: data-hub-admin
      email: data-hub-admin@example.com
      firstName: Data hub
      lastName: Admin
      password: admin
      clientRoles:
        realm-management:
          - manage-realm
          - query-users
          - manage-users
          - query-groups
    demo:
      username: demo
      email: demo-udh-platform@example.com
      firstName: Demo
      lastName: User
      password: demo
  smtp:
    fromDisplayName: keycloak-local
    auth: false
    ssl: false
  integrationTestClient: true

database:
  shadowTables: true

mailpit:
    auth:
        users:
            admin: admin

fakeCa:
  enabled: true
  # openssl req -new -x509 -days 3650 -keyout ca.key -out doc/local-ca.crt -subj "/CN=udp" -addext "basicConstraints=critical,CA:TRUE" -addext "keyUsage=critical,keyCertSign" -addext "nameConstraints=permitted;DNS:.data-hub.local" -nodes
  privateKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC3YgJauWazChqH
    MTwY4rkcegu5lH8HdTm87WV/D5Io0+znkIZi27I1eCFPJd48Tj+tBa1YF5HYhRFb
    rOX0zKVDDyUF+u9pcvK6wWcJWpTiJoUvMKfTocbdN8KrMIJAowgD+0Fs+/Ew+HFe
    YKbbG8caG4RtGwFHJ4kk86OavNX9W1VqvT52d7k9kVb3Z/rS60nljMQI0Q/2bFo0
    1TsTJl83gomEk+Kh1DaJPvuTLNz0MldxZ7mh9xA/Em5jmJYGL5YFVZcUAeBsKyoe
    Ubw5ixCk46D2DG6DEgjzNAOhbxcqm0izQlsozRcuoBpLamIRlKrZ/zDG/CFXUtQg
    ntclJ9i1AgMBAAECggEAAeCOi1XQdmXi4ncdsh8vWdpbazO1d7uo0tchmkMBdZiW
    bpgPuXAPkKOcB3To6uLzKxUpbvTVQPJXisjkcWLtdAnq5gVM/Aju8VGD5D9Qp3Pf
    qIgWx0PXfCcsDalkCpv0LaJ6RABqjxwv8nTm4T3OIoj5vfiB/d5xw6TR0yoIvtkI
    XcXeK17xsEZPMcLHZBbZUXEH7H22ZvDI4ngz0lDG2p4ob5qOhv28uVrB5o7suZz3
    mObxG6Q+bUpz8qkFiGp33QC1ymeZT3NbmeS3IuiwAypZJYpRwiuap6Xfqum5H0U0
    UWRFGcj0a1rnqsb7rHG4UC8aJWLbuy+EAhXj0xJHeQKBgQDaJPh096VGlQwApubF
    xYGuwnIk1oZrZBsPwpssGJkvqS85myamj2mHk88PYVPnqukYv9W8/f8hk2imDDC+
    d0/E0m7sCFK6srdg95VqbYj9R1wuTdPWhZ/OHC6ykxb5WL9aFCkAhOu4UuNlsjU1
    u/M+DoxtFfcD0LvtNZNWxXPb3QKBgQDXNMMEh+0wrL2M0F8v3ce0nVj1bfBJewWO
    nO7DBeX7DVcjseK3mKuki95XMpT6dz+aecc8v8aYV3tOVb4Sxa+0D1o+ivqh7TjU
    g5ZUFNrPwwYoUdKy4CBI13nsUjGleFsDae2GrDZDEEYoT/1G7P8VYa6n0WluXZcH
    jHU0+vluuQKBgCfZgRm885BFQgAMfTO7tMj79GYOWlfb3aWvYzFW/QTb3yii0xiy
    MhD2S2j/2pgDfLlssdroe2biyscqiu0AVq4Z0vGDQ7mfVCh+kejzQYcjNg+vX/dc
    SakZNN6iSBwcvjfyXtsdbQIrAidduqKqRvEbL0PuM0WbJ/lZRCUhxNxxAoGASiS4
    Z7A47MMmzwPfN4uOSVDInE4TMg27XWX98Jzwniz7b6XSuXRU9mzl3l7j6uL4u8zm
    8qwTzNqe9d8ejDMllMCRU+jn7q/fG4B2Y2OH+3pyfaOrFsuW8+Gg9OVgi2TK3oM5
    PWPJkhNiSHM+jJgMTh6IYPMKAuclqIkgvG8XTqkCgYAS8H/IhyYgKUiEJJslNKta
    G0hXLwrwqj2OYirNUuuVUs1cbJkCyVM1u9f1/LteEP7+rysQKwbywogn2zBVq7jn
    iPSJmqnGR1vdLcinYD3hxbpE9KjWwPwBYCwF2FuAkHuJrv33KXp1dSURjzk6rwwf
    gw5h/pp6HAGlLYuYw4rWaQ==
    -----END PRIVATE KEY-----
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDLzCCAhegAwIBAgIUFG/wl6OdtejLdWaHRVWnWNYqwDgwDQYJKoZIhvcNAQEL
    BQAwDjEMMAoGA1UEAwwDdWRwMB4XDTI1MDQyODA4MjI1MloXDTM1MDQyNjA4MjI1
    MlowDjEMMAoGA1UEAwwDdWRwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAt2ICWrlmswoahzE8GOK5HHoLuZR/B3U5vO1lfw+SKNPs55CGYtuyNXghTyXe
    PE4/rQWtWBeR2IURW6zl9MylQw8lBfrvaXLyusFnCVqU4iaFLzCn06HG3TfCqzCC
    QKMIA/tBbPvxMPhxXmCm2xvHGhuEbRsBRyeJJPOjmrzV/VtVar0+dne5PZFW92f6
    0utJ5YzECNEP9mxaNNU7EyZfN4KJhJPiodQ2iT77kyzc9DJXcWe5ofcQPxJuY5iW
    Bi+WBVWXFAHgbCsqHlG8OYsQpOOg9gxugxII8zQDoW8XKptIs0JbKM0XLqAaS2pi
    EZSq2f8wxvwhV1LUIJ7XJSfYtQIDAQABo4GEMIGBMB0GA1UdDgQWBBTFTag9MjKs
    ujfL2GRTEqARySQzTjAfBgNVHSMEGDAWgBTFTag9MjKsujfL2GRTEqARySQzTjAP
    BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwICBDAeBgNVHR4EFzAVoBMwEYIP
    LmRhdGEtaHViLmxvY2FsMA0GCSqGSIb3DQEBCwUAA4IBAQBtcds3I4Psz0F75kAN
    Na9UFuTnmLFgNKlUzr9PpFIBhka5aFOdAZomLRgRhAYDrBW4guj1VlzXXKWHE3WV
    XYXjE2XX39cu1tXB2Y/KT0trjpZbNvjfFuEIdAnDY+xkJdfSa8OEuULVFujvOVUM
    OMohL/AoNak8hIPcHKmaZS5lrXEAA+yJ70aiPBF7Jk5RiRAyv6O5jQkMEEk1qYez
    t2JZCq2IRRReXr7ztYAan8TEMNhS//Hacfbum9dQv1MAl+yOfD2p1Q/cmAC++MF5
    yJbNAMrb/CQIcuHZA3UejXWmGKP1Dh9IlATee3MpYD8+PGj53G4CVCJ/QyH8GbJO
    u2O+
    -----END CERTIFICATE-----

  name: "udh-test-iss"

objectStorage:
  enabled: false

grafanaPublicSync:
  syncIntervalSeconds: 3
  image:
    repository: grafana-public-sync
    pullPolicy: IfNotPresent

mimir:
  config:
    ingester:
      replicas: 2
      zoneAwareReplication:
        enabled: false
    querier:
      replicas: 1
    query_scheduler:
      replicas: 1
    store_gateway:
      zoneAwareReplication:
        enabled: false

geojsonExport:
  image:
    repository: geojson-export
    pullPolicy: IfNotPresent

sensorIngestion:
  metadataDB:
    migrations:
      image:
        registry: "localhost:5000"
        pullPolicy: IfNotPresent
        repository: sensor-ingestion/metadata-db/migrations
    frontend:
      image:
        registry: "localhost:5000"
        pullPolicy: IfNotPresent
        repository: sensor-ingestion/metadata-db/frontend
      # sentry:
      #   dsn: "https://b9d6941e30a946fbb7015038e4b7d923@glitchtip.stg.teuto.dev/5"
    postgraphile:
      image:
        registry: "localhost:5000"
        pullPolicy: IfNotPresent
        repository: sensor-ingestion/metadata-db/postgraphile
  lorawanReceiver:
    image:
      pullPolicy: IfNotPresent
      repository: lorawan-receiver
  prometheusWriter:
    prometheus:
      url: https://prometheus.data-hub.local/api/v1/write
    image:
      pullPolicy: IfNotPresent
      repository: prometheus-remote-write