global:
  auth:
    issuer: https://login.example.com/exampleIssuer
    tokenPath: protocol/openid-connect/token
    readyPath: /
  baseDomain: example.com
  udhImageTag: latest
  udhImageRegistry: "registry-gitlab.teuto.net"
  smtp_base_domain: udh-platform@example.com
  imageCredentials:
    udh-platform:
      host: "registry-gitlab.teuto.net"
      username: "udh-pull-secret"
      password: SECRET
  imagePullSecrets:
    - udh-udh-platform-pullsecret-udh-platform
  storageClass: teutostack-ssd
  babashka:
    image:
      registry: "docker.io"
      pullPolicy: Always
      repository: "babashka/babashka"
      tag: 1.13.219
      digest: ""
  basePipeline:
    image:
      registry: tickets.teuto.net:5050
      repository: teuto-public/base-pipeline/base-pipeline
      tag: v2.0.28
  busybox:
    image:
      registry: "docker.io"
      repository: busybox
      tag: 1.38.0
  sslInsecureSkipVerify: false
  ingress:
    annotations:
      kubernetes.io/tls-acme: "true"
  loglevel: info
  testDeployment: false
keycloak:
  realm: udh
  replicas: 1
  debug: false
  logLevel: info # see https://www.keycloak.org/server/logging for more complex values
  extensions:
    image:
      registry: "registry-gitlab.teuto.net"
      pullPolicy: Always
      repository: "4teuto/dev/udh/teuto-data-hub/keycloak-extensions"
      tag: ""
      digest: ""
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  resources:
    requests:
      cpu: 20m
      memory: 512Mi
    limits:
      memory: 3072Mi
  testUsers: null
  smtp:
    fromDisplayName: keycloak-config-cli
    host: mailing.example.com
    auth: true
    port: 25
    ssl: false
    user: username
    password: password
  integrationTestClient: false

mailpit:
  enabled: true
  image:
    registry: docker.io
    repository: axllent/mailpit
    tag: v1.30.7
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 2
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 2
    successThreshold: 1
  resources:
    requests:
      memory: 32Mi
      cpu: 10m
    limits:
      memory: 96Mi
      cpu: 100m
  ingress:
    annotations: {}
  auth:
    users: {}

cloudnativePostgres:
  image:
    registry: ghcr.io
    repository: teutonet/oci-images/cnpg
    tag: 16.2.0
  replicas: 1
  persistence:
    size: 4Gi
  shadowTables: false

grafana:
  replicas: 1
  image:
    registry: "registry-gitlab.teuto.net"
    repository: 4teuto/dev/udh/teuto-data-hub/grafana
  ingress:
    annotations: {}
  smtp:
    enabled: true
    from_adress: alert@example.com
    from_name: Grafana
    host: mailing.example.com
    user: username
    password: password
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      memory: 1Gi
  plugins:
    - volkovlabs-echarts-panel
    - marcusolsson-dynamictext-panel
    - yesoreyeram-infinity-datasource

grafanaOauth2Proxy:
  resources:
    requests:
      cpu: 20m
      memory: 100Mi
    limits:
      memory: 300Mi

grafanaPublic:
  replicas: 1
  ingress:
    annotations: {}
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      memory: 1Gi
  plugins:
    - volkovlabs-echarts-panel
    - marcusolsson-dynamictext-panel
  datasources:
    {}

prometheus:
  ingress:
    annotations: {}

prometheusOauth2Proxy:
  resources:
    requests:
      cpu: 20m
      memory: 100Mi
    limits:
      memory: 300Mi

jupyterhub:
  ingress:
    annotations: {}
  proxy:
    chp:
      resources:
        requests:
          cpu: 20m
          memory: 256Mi
        limits:
          memory: 1024Mi
    traefik:
      resources:
        requests:
          cpu: 20m
          memory: 256Mi
        limits:
          memory: 1024Mi
    secretSync:
      resources:
        requests:
          cpu: 20m
          memory: 256Mi
        limits:
          memory: 1024Mi
  hub:
    resources:
      requests:
        cpu: 20m
        memory: 256Mi
      limits:
        memory: 1024Mi
  prePuller:
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 1024Mi
  notebook:
    image:
      registry: "registry-gitlab.teuto.net"
      pullPolicy: Always
      repository: "4teuto/dev/udh/teuto-data-hub/jupyterhub-notebook"
      tag: ""
      digest: ""
  singleuser:
    storageCapacity: 1Gi
    allowPrivateIPs: false

mimir:
  externalS3:
    enabled: false
    endpoint: ""
    accessKeyId: ""
    secretAccessKey: ""
    insecure: false
    rulerBucket: "mimir-ruler"
    blocksBucket: "mimir-tsdb"
  config:
    minio:
      enabled: false
    kafka:
      enabled: false
    mimir:
      structuredConfig:
        ingest_storage:
          enabled: false
        ingester:
          push_grpc_method_enabled: true
        tenant_federation:
          enabled: true
        limits:
          # Enable TSDB block upload
          compactor_block_upload_enabled: true
          out_of_order_time_window: 24h
        query_scheduler:
          max_outstanding_requests_per_tenant: 10000
        alertmanager_storage:
          backend: s3
          s3:
            endpoint: ${S3_ENDPOINT}
            bucket_name: ${S3_ALERTMANAGER_BUCKET}
            access_key_id: ${S3_ACCESS_KEY_ID}
            secret_access_key: ${S3_SECRET_ACCESS_KEY}
            insecure: ${S3_INSECURE}
        blocks_storage:
          backend: s3
          s3:
            endpoint: ${S3_ENDPOINT}
            bucket_name: ${S3_BLOCKS_BUCKET}
            access_key_id: ${S3_ACCESS_KEY_ID}
            secret_access_key: ${S3_SECRET_ACCESS_KEY}
            insecure: ${S3_INSECURE}
        ruler_storage:
          backend: s3
          s3:
            endpoint: ${S3_ENDPOINT}
            bucket_name: ${S3_RULER_BUCKET}
            access_key_id: ${S3_ACCESS_KEY_ID}
            secret_access_key: ${S3_SECRET_ACCESS_KEY}
            insecure: ${S3_INSECURE}

fakeCa:
  enabled: false
  generate: false
  certificate: ""
  privateKey: ""
  name: ""

objectStorage:
  enabled: true
  allowDeletion: false
  storage: 5Gi
  monStorage: 5Gi
  singleNode: false
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  operator:
    enabled: false
  reuseClusterFromNamespace: ""

grafanaPublicSync:
  syncIntervalSeconds: 60
  loglevel: info
  image:
    registry: "registry-gitlab.teuto.net"
    repository: 4teuto/dev/udh/teuto-data-hub/grafana-public-sync

geojsonExport:
  podMonitor: true
  replicas: 1
  image:
    registry: "registry-gitlab.teuto.net"
    repository: 4teuto/dev/udh/teuto-data-hub/geojson-export
  ingress:
    annotations: {}

doc:
  enabled: true
  replicas: 1
  image:
    registry: "registry-gitlab.teuto.net"
    repository: 4teuto/dev/udh/teuto-data-hub/doc
  ingress:
    annotations: {}

sensorIngestion:
  networkPolicy:
    # false will disable all NetworkPolicy resources in this chart
    enabled: true
    # if enabled allows ingress from everywhere and egress to public IPv4 addresses for all components that might have to communicate with external services in that direction
    # change this to false if you want to configure fine-grained rules, for example with DNS-specific rules functionality of your CNI
    broadAllowRules: true
  metadataDB:
    enabled: true
    frontend:
      replicas: 1
      image:
        repository: 4teuto/dev/udh/teuto-data-hub/mdb-frontend
        #pullPolicy: Never|IfNotPresent|Always
        pullSecrets: []
      ingress:
        annotations: {}
      sentry:
        dsn: ''
      resources:
        requests:
          memory: 128Mi
          cpu: 10m
        limits:
          memory: 384Mi
          cpu: 100m
    migrations:
      image:
        repository: 4teuto/dev/udh/teuto-data-hub/mdb-migrations
        #pullPolicy: Never|IfNotPresent|Always
        pullSecrets: []
      resources: &default_node_resources
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 256Mi
    postgraphile:
      replicas: 1
      #loglevel: DEBUG|INFO|WARNING|ERROR|CRITICAL
      auth:
        audience: mdb
      ingress:
        enabled: true
        annotations: {}
        client: mdb
        scope: openid
      image:
        repository: 4teuto/dev/udh/teuto-data-hub/mdb-postgraphile
        #pullPolicy: Never|IfNotPresent|Always
        pullSecrets: []
      resources: *default_node_resources
  lorawanReceiver:
    enabled: true
    #loglevel: DEBUG|INFO|WARNING|ERROR|CRITICAL
    targets: &all_targets
      - prometheus-writer
      # - sensor-things-writer
      #- https://other-target.example.com/api/v1/some-write-path
    ingress:
      enabled: true
      annotations: {}
    image:
      repository: 4teuto/dev/udh/teuto-data-hub/lorawan-receiver
      #pullPolicy: Never|IfNotPresent|Always
      pullSecrets: []
    resources: &default_python_resources
      requests:
        memory: 32Mi
        cpu: 50m
      limits:
        memory: 128Mi
  sensorTransformer:
    enabled: true
    replicas: 1
    #loglevel: DEBUG|INFO|WARNING|ERROR|CRITICAL
    targets:
      - prometheus-writer
      # - sensor-things-writer
      #- https://other-target.example.com/api/v1/some-write-path
    ingress:
      enabled: true
      annotations: {}
    image:
      repository: 4teuto/dev/udh/teuto-data-hub/sensor-transformer
      #pullPolicy: Never|IfNotPresent|Always
      pullSecrets: []
    resources: &default_python_resources #to be changed
      requests:
        memory: 32Mi
        cpu: 50m
      limits:
        memory: 128Mi
  jsonataSidecar:
    image:
      repository: 4teuto/dev/udh/teuto-data-hub/jsonata-sidecar
      #pullPolicy: Never|IfNotPresent|Always
    resources: &default_python_resources #to be changed
      requests:
        memory: 32Mi
        cpu: 50m
      limits:
        memory: 128Mi
  prometheusWriter:
    enabled: true
    #loglevel: DEBUG|INFO|WARNING|ERROR|CRITICAL
    outOfOrderSeconds: 0
    alwaysUpdatePayload: true
    ingress:
      enabled: true
      annotations: {}
    prometheus:
      forwardToken: true
      url: https://prometheus.example.com/api/v1/write
      readyPath: /ready
    image:
      repository: 4teuto/dev/udh/teuto-data-hub/prometheus-remote-write
      #pullPolicy: Never|IfNotPresent|Always
      pullSecrets: []
  owmCollector: 
    resources: *default_python_resources
    image:
      repository: 4teuto/dev/udh/teuto-data-hub/owm-collector
    owmApiEndpoint: "https://api.openweathermap.org/data/2.5/weather"
    logLevel: "INFO"
  owmFakeApi:
    image:
      repository: 4teuto/dev/udh/teuto-data-hub/owm-fake-api
      pullSecrets: []
    enabled: true
  resources: *default_python_resources

testAutoProvision:
  writeSensorData: true