[package]
name = "geojson-export"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
bytes = "1.10.1"
chrono = "0.4.41"
deadpool-postgres = "0.14.1"
geohash = "0.13.1"
geojson = "1.0.0"
mime = "0.3.17"
prometheus-http-query = { version = "0.9.0", default-features = false }
promql-parser = "0.10.0"
reqwest = { version = "0.13.3", default-features = false }
rustls = { version = "0.23.31", default-features = false, features = ["ring"] }
rustls-pemfile = "2.2.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["rt", "macros", "signal"] }
tokio-postgres = "0.7.13"
tokio-postgres-rustls = "0.14.0"
tower-http = { version = "0.7.0", features = ["compression-br", "compression-deflate", "compression-gzip", "compression-zstd", "cors", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
