---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook
spec:
  interval: 1h0m0s
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: v1.13.x
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook
  interval: 1h0m0s
  targetNamespace: rook-ceph
  install:
    createNamespace: true
  values:
    csi:
      enableRbdDriver: false
      enableCephfsDriver: false
