policies:
  - type: commit
    spec:
      header:
        length: 72
        imperative: true
        case: upper
        invalidLastCharacters: .
      dco: true
      spellcheck:
        locale: US
