{{- define "udh.fakeCa.caWithoutMetadata" }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
{{- if .Values.fakeCa.generate }}
data:
  tls.crt: {{ include "common.secrets.lookup" (dict "secret" .name "key" "tls.crt" "defaultValue" .ca.Cert "context" $) }}
  tls.key: {{ include "common.secrets.lookup" (dict "secret" .name "key" "tls.key" "defaultValue" .ca.Key "context" $) }}
  ca.crt: {{ .cacrt }}
{{- else }}
stringData:
  tls.crt: {{ .Values.fakeCa.certificate | required "certificate is required" | quote }}
  tls.key: {{ .Values.fakeCa.privateKey | required "certificate key is required" | quote }}
  ca.crt: {{ .Values.fakeCa.certificate | required "certificate is required" | quote }}
{{- end }}
{{- end }}

# where to put rook CA bundle if we need one?
{{ define "udh.fakeCa.rookCaMetadata" -}}
{{- if and .Values.objectStorage.enabled .Values.objectStorage.reuseClusterFromNamespace -}}
name: {{ printf "ns-%s-ca" .Release.Namespace | quote }}
namespace: {{ .Values.objectStorage.reuseClusterFromNamespace | quote }}
{{- else }}
name: {{ printf "%s-ca" .Values.fakeCa.name | quote }}
{{- end }}
{{- end }}

{{- if .Values.fakeCa.enabled }}
{{- $name := .Values.fakeCa.name -}}

# generate if necessary
{{ $ca := "" -}}
{{- $cacrt := "" -}}
{{- if .Values.fakeCa.generate }}
{{- $ca = genCA "ca" 3650 -}}
{{- $cacrt = include "common.secrets.lookup" (dict "secret" $name "key" "ca.crt" "defaultValue" $ca.Cert "context" $) -}}
{{- end }}

# cert-manager CA
{{ include "udh.fakeCa.caWithoutMetadata" (merge (dict "name" $name "ca" $ca "cacrt" $cacrt) .) }}
metadata:
  name: {{ $name | quote }}

# issuer in own namespace
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $name | quote }}
spec:
  ca:
    secretName: {{ $name | quote }}

{{- if .Values.objectStorage.enabled }}
# rook CA bundle
{{ if .Values.fakeCa.generate }}
---
apiVersion: v1
kind: Secret
metadata: {{- include "udh.fakeCa.rookCaMetadata" . | nindent 2 }}
type: Opaque
data:
  cabundle: {{ include "common.secrets.lookup" (dict "secret" $name "key" "ca.crt" "defaultValue" $ca.Cert "context" $) }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata: {{- include "udh.fakeCa.rookCaMetadata" . | nindent 2 }}
type: Opaque
stringData:
  cabundle: {{ .Values.fakeCa.certificate | required "certificate is required" | quote }}
{{- end }}

# do we need to duplicate our fake CA + issuer into the cluster namespace if reusing a Rook Ceph cluster?
{{ if .Values.objectStorage.reuseClusterFromNamespace -}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "ns-%s" .Release.Namespace | quote }}
  namespace: {{ .Values.objectStorage.reuseClusterFromNamespace | quote }}
spec:
  ca:
    secretName: {{ printf "ns-%s" .Release.Namespace | quote }}
---
{{- include "udh.fakeCa.caWithoutMetadata" (merge (dict "name" $name "ca" $ca "cacrt" $cacrt) .) }}
metadata:
  name: {{ printf "ns-%s" .Release.Namespace | quote }}
  namespace: {{ .Values.objectStorage.reuseClusterFromNamespace | quote }}
{{- end -}}
{{- end -}}
{{- end -}}
