{{- if .Values.fakeCa.enabled }}
{{- $name := .Values.fakeCa.name -}}
{{- if .Values.fakeCa.generate }}
{{- $ca := genCA "ca" 3650 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ include "common.secrets.lookup" (dict "secret" $name "key" "tls.crt" "defaultValue" $ca.Cert "context" $) }}
  tls.key: {{ include "common.secrets.lookup" (dict "secret" $name "key" "tls.key" "defaultValue" $ca.Key "context" $) }}
  ca.crt: {{ include "common.secrets.lookup" (dict "secret" $name "key" "ca.crt" "defaultValue" $ca.Cert "context" $) }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | quote }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.fakeCa.certificate | required "certificate is required" | quote }}
  tls.key: {{ .Values.fakeCa.privateKey | required "certificate key is required" | quote }}
  ca.crt: {{ .Values.fakeCa.certificate | required "certificate is required" | quote }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $name | quote }}
spec:
  ca:
    secretName: {{ $name | quote }}
{{- end -}}
