---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "grafana-public") }}
spec:
  releaseName: {{ include "data-hub.name" (dict "context" . "name" "grafana-public") }}
  chart:
    spec:
      chart: grafana
      version: 8.8.2 # renovate: datasource=helm depName=grafana versioning=helm registryUrl=https://grafana.github.io/helm-charts
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: {{ include "data-hub.name" (dict "context" . "name" "grafana") }}
  interval: 1h0m0s
  targetNamespace: {{ .Release.Namespace }}
  values:
    replicas: {{ .Values.grafanaPublic.replicas }}
    {{- if gt (.Values.grafanaPublic.replicas | int64) 1 }}
    podDisruptionBudget:
      minAvailable: 1
    {{- end }}
    ingress:
      enabled: true
      hosts:
        - dashboard-public.{{ .Values.global.baseDomain }}
      annotations: {{- include "udh.ingress.annotations" (dict "context" . "annotations" .Values.grafanaPublic.ingress.annotations) | nindent 8 }}
      tls:
        - hosts:
          - dashboard-public.{{ .Values.global.baseDomain }}
          secretName: dashboard-public.{{ .Values.global.baseDomain }}-tls
    extraSecretMounts:
      - name: secret-files-postgres
        mountPath: /etc/secrets/postgres
        secretName: {{ printf "grafana-public-owner-user.%s-postgres.credentials.postgresql.acid.zalan.do" (include "common.names.fullname" .) | quote }}
        readOnly: true
    grafana.ini:
      auth.anonymous:
        enabled: true
      database:
        type: postgres
        name: grafana_public
        ssl_mode: require
        user: $__file{/etc/secrets/postgres/username}
        password: $__file{/etc/secrets/postgres/password}
        host: {{ printf "%s-postgres:5432" (include "common.names.fullname" .) }}
      security:
        allow_embedding: true
    resources: {{- $.Values.grafanaPublic.resources | toYaml | nindent 6 }}
    rbac:
      create: false
    plugins:
      {{- include "common.tplvalues.render" (dict "value" .Values.grafana.plugins "context" .) | nindent 6 }}
    datasources:
      {{- .Values.grafanaPublic.datasources | toYaml | nindent 6 -}}
