---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "grafana-public") }}
spec:
  releaseName: {{ include "data-hub.name" (dict "context" . "name" "grafana-public") }}
  chart:
    spec:
      chart: grafana
      version: 13.2.4 # renovate: datasource=docker depName=ghcr.io/grafana-community/helm-charts/grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: {{ include "data-hub.name" (dict "context" . "name" "grafana") }}
  interval: 1h0m0s
  targetNamespace: {{ .Release.Namespace }}
  values:
    replicas: {{ .Values.grafanaPublic.replicas }}
    {{- if gt (.Values.grafanaPublic.replicas | int64) 1 }}
    podDisruptionBudget:
      minAvailable: 1
    {{- end }}
    {{- with .Values.grafanaPublic.adminPassword }}
    adminPassword: {{ . }}
    {{- end }}
    extraSecretMounts:
      - name: secret-files-postgres
        mountPath: /etc/secrets/postgres
        secretName: {{ include "data-hub.postgres.secret" (dict "context" . "name" "grafana-public-owner-user" ) }}
        readOnly: true
    grafana.ini:
      auth.anonymous:
        enabled: true
      news:
        news_feed_enabled: false
      database:
        type: postgres
        name: grafana_public
        ssl_mode: require
        user: $__file{/etc/secrets/postgres/username}
        password: $__file{/etc/secrets/postgres/password}
        host: {{ printf "%s:5432" (include "data-hub.postgres.hostRW" .) }}
      security:
        allow_embedding: true
    resources: {{- $.Values.grafanaPublic.resources | toYaml | nindent 6 }}
    rbac:
      create: false
    plugins:
      {{- include "common.tplvalues.render" (dict "value" .Values.grafana.plugins "context" .) | nindent 6 }}
    datasources:
      {{- .Values.grafanaPublic.datasources | toYaml | nindent 6 -}}
{{ $host := printf "dashboard-public.%s" .Values.global.baseDomain }}
{{ $name := "grafana-public" }}
{{ include "udh.gatewayapi.gateway" (dict "context" $ "name" $name "host" $host) }}
{{ include "udh.gatewayapi.https-redirect" (dict "context" $ "name" $name "host" $host) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-%s" (include "common.names.fullname" .) $name }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  hostnames:
  - {{ $host }}
  parentRefs:
  - name: {{ printf "%s-%s" (include "common.names.fullname" .) $name }}
    sectionName: https
  rules:
  - backendRefs:
    - name: {{ printf "%s-%s" (include "common.names.fullname" .) $name }}
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
