---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "grafana") }}
spec:
  interval: 1h0m0s
  url: https://grafana.github.io/helm-charts
