{{- $owmClientSecretSpec := (merge (dict "name" "owm-secret") .) -}}
{{- $owmClientSecret := include "udh.secret" $owmClientSecretSpec }}
{{ include "udh.secretManifest" (merge (dict "value" $owmClientSecret) $owmClientSecretSpec) }}
---
{{- $autoProvisioningClientSecretSpec := (merge (dict "name" "auto-provisioning-client-secret") .) -}}
{{- $autoProvisioningClientSecret := include "udh.secret" $autoProvisioningClientSecretSpec }}
{{ include "udh.secretManifest" (merge (dict "value" $autoProvisioningClientSecret) $autoProvisioningClientSecretSpec) }}
---
{{- $grafanaClientSecretSpec := (merge (dict "name" "grafana-client-secret") .) -}}
{{- $grafanaClientSecret := include "udh.secret" $grafanaClientSecretSpec }}
{{ include "udh.secretManifest" (merge (dict "value" $grafanaClientSecret) $grafanaClientSecretSpec) }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "keycloak") }}
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/teutonet/keycloak-chart/keycloak
  ref:
    tag: 1.1.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "keycloak") }}
spec:
  releaseName: {{ include "data-hub.name" (dict "context" . "name" "sso") }}
  chartRef:
    kind: OCIRepository
    name: {{ include "data-hub.name" (dict "context" . "name" "keycloak") }}
  interval: 1h0m0s
  timeout: 15m
  targetNamespace: {{ .Release.Namespace }}
  dependsOn: [
    {{- if and .Values.objectStorage.enabled (not .Values.objectStorage.reuseClusterFromNamespace) }}
    name: {{ include "data-hub.name" (dict "context" . "name" "rook-ceph-cluster") | quote }},
    {{- end }}
    name: {{ include "data-hub.name" (dict "context" . "name" "grafana") }}
  ]
  values:
    {{- with .Values.keycloak.adminAuth }}
    auth:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    postgres:
      enabled: false
    replicaCount: {{ .Values.keycloak.replicas }}
    externalDatabase:
      host: {{ include "data-hub.postgres.hostRW" . }}
      port: 5432
      database: keycloak
      existingSecret: {{ include "data-hub.postgres.secret" (dict "context" . "name" "keycloak-owner-user" ) }}
      existingSecretUserKey: "username"
      existingSecretPasswordKey: "password"
    extraStartupArgs: --features=admin-fine-grained-authz:v2{{ if .Values.global.trustCaSecretName }} -Djavax.net.ssl.trustStore=/tmp/cacerts{{ end }}{{ if .Values.keycloak.debug }} --debug 5005{{ end }}
      --http-enabled=true --proxy-headers xforwarded
      {{ if .Values.keycloak.integrationTestClient }} --spi-brute-force-protector-default-brute-force-detector-allow-concurrent-requests=true{{ end }}
    production: true
    # The keycloak chart expects a list of strings, not a map
    {{- $imagePullSecrets := get (include "udh-platform.imagePullSecrets" (dict "context" .) | fromYaml) "imagePullSecrets" }}
    global:
      security:
        allowInsecureImages: true
      {{- if $imagePullSecrets }}
      imagePullSecrets:
      {{- range $entry := $imagePullSecrets }}
        - {{ get $entry "name" }}
      {{- end }}
      {{- end }}
    service:
      type: ClusterIP
      http:
        enabled: false
    resources: {{- $.Values.keycloak.resources | toYaml | nindent 6 }}
    image:
      tag: 26.7.0 # renovate: datasource=docker depName=keycloak/keycloak
    ingress:
      enabled: true
      hostname: {{ include "data-hub.keycloak.hostname" . }}
      tls: true
      servicePort: https
      annotations: {{- include "udh.ingress.annotations" (dict "context" $ "annotations" .Values.keycloak.ingress.annotations) | nindent 8 }}
        nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "https://{{ (include "sensor-ingestion.mdb.frontend.hostname" .) }}"
    tls:
      enabled: true
      autoGenerated:
        enabled: true
    cache:
      stack: kubernetes

    httpEnabled: true
    proxyHeaders: xforwarded
    
    extraVolumes:
      {{- if .Values.global.trustCaSecretName }}
      - name: ca-cert
        secret:
          secretName: {{ .Values.global.trustCaSecretName }}
          items:
          - key: ca.crt
            path: ca.crt
      {{- end }}
    extraVolumeMounts:
      {{- if .Values.global.trustCaSecretName }}
      - mountPath: /tls
        readOnly: true
        name: ca-cert
      {{- end }}
    args:
      - -c
      - |
        {{- if .Values.global.trustCaSecretName }}
        cp /etc/pki/java/cacerts /tmp/
        chmod u+w /tmp/cacerts
        keytool -import -keystore /tmp/cacerts -storepass changeit -noprompt < /tls/ca.crt
        {{- end }}

        # continue with upstream command
        exec /opt/keycloak/bin/kc.sh $KEYCLOAK_EXTRA_ARGS_PREPENDED start $KEYCLOAK_EXTRA_ARGS
    initContainers:
      - name: extensions
        image: {{ include "udh-platform.images.keycloak.extensions" (dict "context" .) }}
        imagePullPolicy: {{ .Values.keycloak.extensions.image.pullPolicy }}
        volumeMounts:
          - mountPath: /target
            name: empty-dir
            subPath: app-providers-dir
    extraEnvVars:
      - name: KEYCLOAK_ENABLE_HEALTH_ENDPOINTS
        value: "true"
      - name: KC_LOG_LEVEL
        value: {{ .Values.keycloak.logLevel | quote }}
      - name: PROMETHEUS_HOST
        value: {{ include "data-hub.name" (dict "context" . "name" "mimir-nginx") }}
      - name: GRAFANA_HOST
        value: {{ include "data-hub.name" (dict "context" . "name" "grafana") }}
      - name: GRAFANA_USER
        valueFrom:
          secretKeyRef:
            name: {{ include "data-hub.name" (dict "context" . "name" "grafana") }}
            key: admin-user
      - name: GRAFANA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{ include "data-hub.name" (dict "context" . "name" "grafana") }}
            key: admin-password
      - name: DATA_HUB_BASEURL
        value: https://{{ .Values.global.baseDomain }}
      {{- if .Values.objectStorage.enabled }}
      - name: BUCKET_ENDPOINT
        value: {{ include "data-hub.storage.hostname" . | printf "https://%s" | quote }}
      - name: BUCKET_SERVICE_ENDPOINT
        value: {{ include "udh.rook-ceph-bucket.service" . }}.svc.cluster.local
      {{- include "udh.objectstore.userEnv" (dict "user" "bucket-admin" "context" .) | nindent 6 }}
      {{- end }}
    keycloakConfigCli:
      enabled: true
      image:
        tag: 6.5.0-26.5.4
      configuration:
        {{ .Values.keycloak.realm }}.yaml: |
          realm: {{ .Values.keycloak.realm }}

          # TODO delete workaround once https://github.com/ceph/ceph/pull/53915 has landed in our clusters
          # more info https://tracker.ceph.com/issues/54562
          components:
            org.keycloak.keys.KeyProvider:
            - name: rsa-generated
              providerId: rsa-generated
              config:
                priority:
                - '150'
          loginTheme: teuto-data-hub
          adminTheme: teuto-data-hub
          adminPermissionsEnabled: true
          internationalizationEnabled: true
          supportedLocales:
            - de
          defaultLocale: de
          {{- if .Values.keycloak.smtp }}
          smtpServer:
            from: {{ printf "keycloak-%s" .Values.global.smtp_base_domain | quote}}
            fromDisplayName: {{ .Values.keycloak.smtp.fromDisplayName | quote}}
            {{- if .Values.mailpit.enabled }}
            host: {{ (printf "%s-%s" (include "common.names.fullname" .) "mailpit-smtp") }}
            {{- else }}
            host: {{ .Values.keycloak.smtp.host | quote}}
            {{- end }}
            port: {{ .Values.keycloak.smtp.port }}
            auth: {{ .Values.keycloak.smtp.auth }}
            ssl: {{ .Values.keycloak.smtp.ssl }}
            envelopeFrom: {{ printf "keycloak-%s" .Values.global.smtp_base_domain | quote}}
            user: {{ .Values.keycloak.smtp.user | quote}}
            password: {{ .Values.keycloak.smtp.password | quote}}
          {{ end -}}
          enabled: true
          loginWithEmailAllowed: true
          rememberMe: true
          bruteForceProtected: true
          internationalizationEnabled: true
          supportedLocales:
            - de
            - en
          defaultLocale: de

          eventsListeners:
            - jboss-logging
            - udh-sync

          clients:
            - clientId: owm-collector
              publicClient: false
              directAccessGrantsEnabled: false
              serviceAccountsEnabled: true
              standardFlowEnabled: false
              clientAuthenticatorType: client-secret
              secret: {{ $owmClientSecret | quote }}
              protocol: openid-connect
              protocolMappers:
                - name: audience
                  protocol: openid-connect
                  protocolMapper: oidc-audience-mapper
                  config:
                    included.client.audience: owm-collector
                    included.custom.audience: owm-collector
                    access.token.claim: 'true'
            - clientId: grafana
              secret: {{ $grafanaClientSecret | quote }}
              publicClient: false
              defaultClientScopes: []
              optionalClientScopes: [email]
              protocol: openid-connect
              baseUrl: https://{{ include "data-hub.grafana.hostname" . }}
              redirectUris:
                - https://{{ include "data-hub.grafana.hostname" . }}/login/generic_oauth
                - https://{{ include "sensor-ingestion.mdb.frontend.hostname" . }}/
              webOrigins:
                - +
              protocolMappers:
                - name: udh-sync
                  protocol: openid-connect
                  protocolMapper: udh-sync
                  config:
                    userinfo.token.claim: 'true'
                    id.token.claim: 'false'
                    access.token.claim: 'false'
            - clientId: jupyterhub
              publicClient: true
              defaultClientScopes: []
              optionalClientScopes: [email, profile]
              redirectUris:
                - https://{{ include "data-hub.jupyterhub.hostname" . }}/hub/oauth_callback
              webOrigins:
                - +
            - clientId: usercode
              standardFlowEnabled: false
              defaultClientScopes: []
              attributes:
                oauth2.device.authorization.grant.enabled: 'true'
              publicClient: true
              optionalClientScopes: [prometheus_read, buckets, data-hub]
              protocolMappers:
                - &udh_sync
                  name: udh-sync
                  protocol: openid-connect
                  protocolMapper: udh-sync
                  config:
                    userinfo.token.claim: 'true'
                    id.token.claim: 'true'
                    access.token.claim: 'true'
            - &mdb
              clientId: mdb
              redirectUris:
                - https://mdb.{{ .Values.global.baseDomain }}/oauth2/callback
              webOrigins:
                - +
              publicClient: true
              defaultClientScopes: []
              optionalClientScopes: []
              attributes:
                access.token.lifespan: 300
              protocolMappers:
                - name: audience-mdb
                  protocol: openid-connect
                  protocolMapper: oidc-audience-mapper
                  config:
                    included.custom.audience: mdb
                    access.token.claim: "true"
                - *udh_sync
            - <<: *mdb
              clientId: mdb-frontend
              baseUrl: https://mdb-frontend.{{ .Values.global.baseDomain }}
              redirectUris:
                - https://mdb-frontend.{{ .Values.global.baseDomain }}/auth/
                - https://mdb-frontend.{{ .Values.global.baseDomain }}/auth/silent/
              optionalClientScopes: [profile, data-hub, buckets]
            - clientId: data-hub
              standardFlowEnabled: false
              serviceAccountsEnabled: true
              authorizationServicesEnabled: true
              defaultClientScopes: []
              publicClient: false
              optionalClientScopes: []
            - clientId: graphiql
              publicClient: true
              baseUrl: https://{{ include "data-hub.keycloak.hostname" . }}/realms/udh/data-hub/graphiql
              standardFlowEnabled: true
              defaultClientScopes: [data-hub]
              optionalClientScopes: []
              redirectUris:
                - https://{{ include "data-hub.keycloak.hostname" . }}/realms/udh/data-hub/graphiql
              webOrigins:
                - +
              attributes:
                pkce.code.challenge.method: S256
            - clientId: auto-provisioning
              clientAuthenticatorType: client-secret
              secret: {{ $autoProvisioningClientSecret | quote }}
              notBefore: 0
              bearerOnly: false
              consentRequired: false
              standardFlowEnabled: false
              implicitFlowEnabled: false
              directAccessGrantsEnabled: false
              serviceAccountsEnabled: true
              publicClient: false
              frontchannelLogout: false
              protocol: openid-connect
              fullScopeAllowed: true
              protocolMappers:
                - name: audience-mdb
                  protocol: openid-connect
                  protocolMapper: oidc-audience-mapper
                  config:
                    included.custom.audience: mdb
                    access.token.claim: "true"
                - *udh_sync
                - &data_hub_audience
                  name: add-aud-data-hub
                  protocol: openid-connect
                  protocolMapper: oidc-audience-mapper
                  consentRequired: false
                  config:
                    included.client.audience: data-hub
                    id.token.claim: "false"
                    access.token.claim: "true"
            {{- if .Values.keycloak.integrationTestClient }}
            - clientId: integration-test
              secret: {{ dig "data-hub-admin" "password" "" .Values.keycloak.testUsers | quote }}
              serviceAccountsEnabled: true
              directAccessGrantsEnabled: true
              protocolMappers:
                - name: add-aud-data-hub
                  protocol: openid-connect
                  protocolMapper: oidc-audience-mapper
                  consentRequired: false
                  config:
                    included.client.audience: data-hub
                    id.token.claim: "false"
                    access.token.claim: "true"
            {{- end }}
          clientScopes:
            - name: prometheus_read
              protocol: openid-connect
              attributes:
                display.on.consent.screen: 'true'
                consent.screen.text: Prometheus API (read)
              protocolMappers:
                - name: audience
                  protocol: openid-connect
                  protocolMapper: oidc-audience-mapper
                  config:
                    included.custom.audience: prometheus_read
                    access.token.claim: 'true'
                    id.token.claim: 'true'
            - name: buckets
              protocol: openid-connect
              attributes:
                display.on.consent.screen: 'true'
                consent.screen.text: Object Storage
              protocolMappers:
                - name: audience
                  protocol: openid-connect
                  protocolMapper: oidc-audience-mapper
                  config:
                    included.custom.audience: buckets
                    id.token.claim: 'true'
            - name: data-hub
              protocol: openid-connect
              attributes:
                display.on.consent.screen: 'true'
                consent.screen.text: Resource Management
              protocolMappers:
                - name: audience
                  protocol: openid-connect
                  protocolMapper: oidc-audience-mapper
                  config:
                    included.custom.audience: data-hub
                    access.token.claim: 'true'

          users:
            {{- if $.Values.keycloak.testUsers }}
            {{- range $user := $.Values.keycloak.testUsers }}
            - username: {{ $user.username | default $user.email | quote }}
              {{- if $user.firstName }}
              firstName: {{ $user.firstName }}
              {{- end }}
              {{- if $user.lastName }}
              lastName: {{ $user.lastName }}
              {{- end }}
              email: {{ $user.email | quote }}
              enabled: True
              emailVerified: True
              realmRoles: {{- $user.realmRoles | default (list) | toYaml | nindent 16 }}
              clientRoles: {{- $user.clientRoles | default (dict) | toYaml | nindent 16 }}
              credentials:
                - type: password
                  value: {{ $user.password | quote }}
            {{- end }}
            {{- end }}
            - username: service-account-auto-provisioning
              serviceAccountClientId: auto-provisioning
              clientRoles:
                realm-management:
                  - manage-realm
                  - query-users
                  - manage-users
                  - query-groups

          {{ define "udh.keycloak.bruteforce" -}}
          # security defenses / brute force detection
          bruteForceProtected: true
          permanentLockout: false
          failureFactor: 30
          waitIncrementSeconds: 60
          quickLoginCheckMilliSeconds: 1000
          minimumQuickLoginWaitSeconds: 60
          maxFailureWaitSeconds: 900
          maxDeltaTimeSeconds: 43200
          {{- end -}}
          {{ include "udh.keycloak.bruteforce" . }}
        master.yaml: |
          realm: master
          {{ include "udh.keycloak.bruteforce" . }}
