{{- define "udh.mimir-s3-env" -}}
{{- if .Values.mimir.externalS3.enabled }}
S3_ENDPOINT: {{ .Values.mimir.externalS3.endpoint | quote }}
S3_ACCESS_KEY_ID: {{ .Values.mimir.externalS3.accessKeyId | quote }}
S3_SECRET_ACCESS_KEY: {{ .Values.mimir.externalS3.secretAccessKey | quote }}
S3_INSECURE: {{ .Values.mimir.externalS3.insecure | quote }}
S3_ALERTMANAGER_BUCKET: {{ .Values.mimir.externalS3.rulerBucket | quote }}
S3_BLOCKS_BUCKET: {{ .Values.mimir.externalS3.blocksBucket | quote }}
S3_RULER_BUCKET: {{ .Values.mimir.externalS3.rulerBucket | quote }}
{{- else -}}
S3_ENDPOINT: {{ include "data-hub.name" (dict "context" . "name" "minio") }}:9000
S3_ACCESS_KEY_ID: admin
S3_SECRET_ACCESS_KEY: supersecret
S3_INSECURE: "true"
S3_ALERTMANAGER_BUCKET: mimir-ruler
S3_BLOCKS_BUCKET: mimir-tsdb
S3_RULER_BUCKET: mimir-ruler
{{- end }}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "mimir") }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "udh.mimir-s3-env" . | nindent 2 }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "mimir") }}
spec:
  releaseName: {{ include "data-hub.name" (dict "context" . "name" "mimir") }}
  chart:
    spec:
      chart: mimir-distributed
      version: 5.6.0 # renovate: datasource=helm depName=mimir-distributed versioning=helm registryUrl=https://grafana.github.io/helm-charts
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: {{ include "data-hub.name" (dict "context" . "name" "grafana") }}
  interval: 1h0m0s
  targetNamespace: {{ .Release.Namespace }}
  values:
    {{- $copiedConfig := mergeOverwrite .Values.mimir.config (dict "global" (dict "extraEnvFrom" (list (dict "secretRef" (dict "name" (include "data-hub.name" (dict "context" . "name" "mimir"))))) "podAnnotations" (dict "checksum/mimir-s3-env" (include "udh.mimir-s3-env" . | sha256sum)) )) }}
    {{ $copiedConfig | toYaml | nindent 4 }}
