{{- define "udh.mimir-s3-env" -}}
{{- if .Values.mimir.externalS3.enabled }}
S3_ENDPOINT: {{ .Values.mimir.externalS3.endpoint | quote }}
S3_ACCESS_KEY_ID: {{ .Values.mimir.externalS3.accessKeyId | quote }}
S3_SECRET_ACCESS_KEY: {{ .Values.mimir.externalS3.secretAccessKey | quote }}
S3_INSECURE: {{ .Values.mimir.externalS3.insecure | quote }}
S3_ALERTMANAGER_BUCKET: {{ .Values.mimir.externalS3.rulerBucket | quote }}
S3_BLOCKS_BUCKET: {{ .Values.mimir.externalS3.blocksBucket | quote }}
S3_RULER_BUCKET: {{ .Values.mimir.externalS3.rulerBucket | quote }}
{{- else -}}
S3_ENDPOINT: {{ include "data-hub.name" (dict "context" . "name" "minio") }}:9000
S3_ACCESS_KEY_ID: admin
S3_SECRET_ACCESS_KEY: supersecret
S3_INSECURE: "true"
S3_ALERTMANAGER_BUCKET: mimir-ruler
S3_BLOCKS_BUCKET: mimir-tsdb
S3_RULER_BUCKET: mimir-ruler
{{- end }}
{{- end -}}
{{- define "udh.mimir.extraValues" -}}
global:
  extraEnvFrom:
    - secretRef:
        name: {{ include "data-hub.name" (dict "context" . "name" "mimir") }}
podAnnotations:
  checksum/mimir-s3-env: {{ include "udh.mimir-s3-env" . | sha256sum | quote }}
gateway:
  service:
    nameOverride: {{ include "data-hub.name" (dict "context" . "name" "mimir-nginx") }}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "mimir") }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "udh.mimir-s3-env" . | nindent 2 }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "mimir-distributed") }}
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/grafana/helm-charts/mimir-distributed
  ref:
    tag: 6.1.0 # renovate: datasource=docker depName=ghcr.io/grafana/helm-charts/mimir-distributed

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "mimir") }}
spec:
  releaseName: {{ include "data-hub.name" (dict "context" . "name" "mimir") }}
  chartRef:
    kind: OCIRepository
    name: {{ include "data-hub.name" (dict "context" . "name" "mimir-distributed") }}
  interval: 1h0m0s
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  targetNamespace: {{ .Release.Namespace }}
  values:
    {{- $copiedConfig := mergeOverwrite
      .Values.mimir.config
      ( include "udh.mimir.extraValues" . | fromYaml ) }}
    {{ $copiedConfig | toYaml | nindent 4 }}
