---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "oauth2") }}
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/oauth2-proxy/charts/oauth2-proxy
  ref:
    tag: 7.9.2 # renovate: datasource=docker depName=ghcr.io/oauth2-proxy/charts/oauth2-proxy
