---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "oauth2") }}
spec:
  interval: 1h0m0s
  url: https://oauth2-proxy.github.io/manifests
