{{- define "udh.jwtIngress" -}}
{{- $cookieSecretMimirOauthProxySpec := (merge (dict "name" (printf "cookie-secret-mimir-oauth-%s" .name)) .) -}}
{{- $cookieSecretMimirOauthProxy := include "udh.secret" $cookieSecretMimirOauthProxySpec }}
{{ include "udh.secretManifest" (merge (dict "value" $cookieSecretMimirOauthProxy) $cookieSecretMimirOauthProxySpec) }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" (printf "%s-%s" "mimir-auth" .name)) }}
spec:
  releaseName: {{ include "data-hub.name" (dict "context" . "name" (printf "%s-%s" "mimir-auth" .name)) }}
  chartRef:
    kind: OCIRepository
    name: {{ printf "%s-oauth2" (include "common.names.fullname" .) | quote }}
  interval: 1h0m0s
  dependsOn:
    - name: {{ include "data-hub.name" (dict "context" . "name" "keycloak") }}
  values:
    replicaCount: {{ .Values.prometheusOauth2Proxy.replicas }}
    config:
      clientID: prometheus_{{ .name }}
      cookieSecret: {{ $cookieSecretMimirOauthProxy | quote }}
      configFile: email_domains = [ "*" ]
    alphaConfig:
      enabled: true
      configData:
        injectRequestHeaders:
        - name: X-Scope-OrgID
          values:
          - claimSource:
              claim: groups
        providers:
        - clientID: prometheus_{{ .name }}
          clientSecret: unused
          code_challenge_method: S256
          id: oidc=prometheus_{{ .name }}
          loginURLParameters:
          - default:
            - force
            name: approval_prompt
          {{- if .Values.fakeCa.name }}
          caFiles:
            - /tls/ca.crt
          {{- end }}
          oidcConfig:
            audienceClaims: [aud]
            emailClaim: sub
            issuerURL: {{ .Values.global.auth.issuer | quote }}
            userIDClaim: email
          provider: oidc
        upstreamConfig:
          upstreams:
          - id: /
            path: {{ .path | quote }}
            rewriteTarget: {{ .target | quote }}
            uri: {{ printf "http://%s/" (include "data-hub.name" (dict "context" . "name" "mimir-nginx") ) | quote }}
    extraArgs:
      skip-provider-button: true
      silence-ping-logging: true
      cookie-refresh: 4m55s
      cookie-csrf-per-request: true
      skip-jwt-bearer-tokens: true
    {{- if .Values.fakeCa.name }}
    extraVolumeMounts:
      - mountPath: /tls
        readOnly: true
        name: ca-cert
    extraVolumes:
      - name: ca-cert
        secret:
          secretName: {{ .Values.fakeCa.name }}
          items:
            - key: ca.crt
              path: ca.crt
    {{- end }}
    resources: {{- $.Values.prometheusOauth2Proxy.resources | toYaml | nindent 6 }}
{{- end -}}
{{- $readPathRegex := "/(api/v1/(?:query|query_range|format_query|query_exemplars|series|labels?)(?:/.*)?)$" -}}
{{- $writePathRegex := "/api/v1/write$" -}}
{{ include "udh.jwtIngress" (merge (dict
  "name" "read"
  "target" "/prometheus/$1"
  "path" $readPathRegex) .) }}
{{ include "udh.jwtIngress" (merge (dict
  "name" "write"
  "target" "/api/v1/push"
  "path" $writePathRegex) .) }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "data-hub.name" (dict "context" . "name" "prometheus") }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations: {{- include "udh.ingress.annotations" (dict "context" . "annotations" .Values.prometheus.ingress.annotations) | nindent 4 }}
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: prometheus.{{ .Values.global.baseDomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "data-hub.name" (dict "context" . "name" "mimir-auth-read-oauth2-proxy") }}
            port:
              number: 80
        path: {{ $readPathRegex | quote }}
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "data-hub.name" (dict "context" . "name" "mimir-auth-write-oauth2-proxy") }}
            port:
              number: 80
        path: {{ $writePathRegex | quote }}
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ include "data-hub.name" (dict "context" . "name" "mimir-auth-write-oauth2-proxy") }}
            port:
              number: 80
        path: /ready$
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - prometheus.{{ .Values.global.baseDomain }}
    secretName: prometheus.{{ .Values.global.baseDomain }}-tls