#!/bin/bash

source "$(dirname "$BASH_SOURCE")/.common"

cd "$(dirname "$0")"

MDB_PATH="$REPO/sensor-ingestion/metadata-db"
MIGRATIONS_PATH="$MDB_PATH/migrations"
FRONTEND_PATH="$MDB_PATH/frontend"

DB_CONTAINER_NAME=pg-schema-db
NETWORK_NAME=db
PGHOST=postgres

function tearDown {
  docker rm -f ${DB_CONTAINER_NAME}
	docker network rm ${NETWORK_NAME}
}

trap tearDown EXIT

docker network create ${NETWORK_NAME}

docker run --rm -dt \
  -v $MIGRATIONS_PATH/migrations/init:/docker-entrypoint-initdb.d:ro \
  -e POSTGRES_PASSWORD=postgres \
  --name ${DB_CONTAINER_NAME} \
  $REGISTRY/postgres
docker network connect --alias ${PGHOST} ${NETWORK_NAME} ${DB_CONTAINER_NAME}

sleep 4

# (cd ../migrations && npm i)
# (cd ../frontend && npm i)

docker run --rm \
	--network ${NETWORK_NAME} \
  -e PGHOST=${PGHOST} \
  -e PGUSER=postgres \
  -e PGPASSWORD=postgres \
  -e PGDATABASE=mdb \
  -e PGSSLMODE=disable \
	-v $MIGRATIONS_PATH:/migrate:ro \
  --entrypoint npx \
  --workdir /migrate \
	$IMAGE_NODE graphile-migrate migrate

docker run --rm \
	--network ${NETWORK_NAME} \
  -e PGHOST=${PGHOST} \
  -e PGUSER=postgres \
  -e PGPASSWORD=postgres \
  -e PGDATABASE=mdb \
  -e PGSSLMODE=disable \
	-v $MIGRATIONS_PATH:/migrate:ro \
  --entrypoint npx \
  --workdir /migrate \
	$IMAGE_NODE graphile-migrate watch --once

docker run --rm \
	--network ${NETWORK_NAME} \
  -e DATABASE_URL=postgres://postgres:postgres@${PGHOST}:5432/mdb \
  -e OUT_SCHEMA_PATH=/frontend/src/lib/common/generated/schema.graphql \
	-v $FRONTEND_PATH:/frontend \
	-u `id -u`:`id -g` \
  --entrypoint /bin/sh \
  --workdir /postgraphile \
	$REGISTRY/sensor-ingestion/metadata-db/postgraphile -c "node build/generate-schema.js"

(cd "$FRONTEND_PATH" && npm run generate-types)
