#!/usr/bin/env bash

source "$(dirname "$BASH_SOURCE")/.common"

cd "$REPO"

: ${MINIKUBE_RESOURCE_CPU:=6}
: ${MINIKUBE_RESOURCE_RAM:=16384}
: ${KUBERNETES_VERSION:=$DEFAULT_KUBERNETES_VERSION}
: ${TELEPRESENCE:=1}

error () {
  printf %s\\n "$1" >&2
  exit 1
}

# required tools

echo "Checking for SOPS"
if ! command -v sops &> /dev/null
then
  echo "SOPS is not installed, exiting"
  echo "install it with 'pacman -Suy sops'"
  exit
fi

echo "Checking for Helm"
if ! command -v helm &> /dev/null
then
  echo "Helm is not installed, exiting"
  echo "install it with 'pacman -Suy helm'"
  exit
fi

echo "Checking for jq"
if ! command -v jq &> /dev/null
then
  echo "jq is not installed, exiting"
  echo "install it with 'pacman -Suy jq'"
  exit
fi

echo "Checking for Minikube"
if ! command -v minikube &> /dev/null
then
  echo "Minikube is not installed, exiting"
  echo "install it with 'pacman -Suy minikube'"
  exit
fi

echo "Checking for Helm-secrets"
if ! helm plugin list | grep -q 'secrets';
then
  echo "Helm-secrets is not installed, exiting"
  echo "please check https://github.com/jkroepke/helm-secrets for installing it"
  exit
fi

minikube_started=false
if [[ `minikube status | grep '\(host\|kubelet\|apiserver\): Running' | wc -l` -eq 3 ]]
then
  echo "minikube already running"
else
  echo "force docker-driver"
  minikube config set driver docker

  echo "starting minikube"
  minikube start --cni=cilium --driver docker --cpus=${MINIKUBE_RESOURCE_CPU} --memory=${MINIKUBE_RESOURCE_RAM} --kubernetes-version=${KUBERNETES_VERSION} --extra-config=apiserver.service-node-port-range=1-32767

  minikube_started=true
fi

if $minikube_started || [ ${MINIKUBE_SETUP:-0} -eq 1 ]
then
  echo "enabling metrics-server"
  minikube addons enable metrics-server

  echo "enabling minikube registry"
  minikube addons enable registry --images="KubeRegistryProxy=registry.k8s.io/minikube/kube-registry-proxy:v0.0.11"
   # Using Cilium as a CNI somehow breaks running the docker registry on localhost:5000 (only on some machines), this is hopefully fixing it 
  $KUBECTL -n kube-system patch svc registry --type json --patch '[{"op":"replace","path":"/spec/type","value":"NodePort"},{"op":"add","path":"/spec/ports/0/nodePort","value":32000}]'

  echo "enabling cert-manager"
  helm upgrade cert-manager --version "$CERT_MANAGER_VERSION" --install --create-namespace -n cert-manager cert-manager --repo https://charts.jetstack.io --set installCRDs=true --wait

  echo "enabling cnpg operator"
  helm upgrade cnpg --version "$CNPG_VERSION" --install  --create-namespace -n cnpg-system cloudnative-pg --repo https://cloudnative-pg.github.io/charts --wait

  echo "enabling traefik ingress"
  helm upgrade traefik --version "$TRAEFIK_VERSION" --install --create-namespace -n traefik traefik --repo https://traefik.github.io/charts --wait \
    --set service.spec.type=NodePort \
    --set providers.kubernetesIngressNGINX.enabled=true \
    --set providers.kubernetesIngressNGINX.watchIngressWithoutClass=true \
    --set ports.web.nodePort=80 \
    --set ports.websecure.nodePort=443

  echo "install podmonitor crd"
  $KUBECTL apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml

  echo "create loop device nodes in minikube"
  minikube ssh </dev/null '
  for i in {0..63}
  do
    sudo mknod /dev/loop$i b 7 $i || true
  done'

  echo "removing problematic device nodes in minikube"
  minikube ssh </dev/null 'sudo rm /dev/dm-* || true'

  echo "install CSI hostpath plugin and dependencies"
  hostpath_repo="$(mktemp -d)"
  git clone --depth 1 -b "$HOSTPATH_VERSION" https://github.com/kubernetes-csi/csi-driver-host-path "$hostpath_repo"
  SNAPSHOTTER_BRANCH="$SNAPSHOTTER_VERSION" eval "$(grep -o 'kubectl apply .*{SNAPSHOTTER_.*' "$hostpath_repo/docs/deploy-1.17-and-later.md" | sed 's/kubectl/$KUBECTL -n kube-system/')"
  sed -i 's/kubectl/$KUBECTL -n default/g' "$hostpath_repo"/deploy/kubernetes-latest/deploy.sh
  KUBECTL="$KUBECTL" "$hostpath_repo"/deploy/kubernetes-latest/deploy.sh
  $KUBECTL apply -f <(sed 's/metadata:/&\n  annotations:\n    storageclass.kubernetes.io\/is-default-class: "true"/' "$hostpath_repo/examples/csi-storageclass.yaml")
  rm -rf "$hostpath_repo"

  echo "enabling rook-ceph"
  helm upgrade rook --version "$ROOK_CEPH_VERSION" --install --create-namespace -n rook-ceph rook-ceph --repo https://charts.rook.io/release --wait --set csi.enableRbdDriver=false  --set csi.enableCephfsDriver=false --set allowLoopDevices=true

  echo "install flux"
  $KUBECTL apply -f https://github.com/fluxcd/flux2/releases/download/$FLUX_VERSION/install.yaml

  if [ $TELEPRESENCE -eq 1 ]; then
    echo "prepare telepresence"
    which telepresence
    rc=$?
    if [ $rc -eq 0 ]; then
      telepresence helm install || true
    fi
  fi
fi

# Verify k8s version
installed_kubernetes_version=$($KUBECTL version -o json 2> /dev/null | jq -r '.serverVersion.gitVersion')
if [[ $installed_kubernetes_version != $KUBERNETES_VERSION ]]
then
  echo "Wrong kubernetes version, you need a server version of $KUBERNETES_VERSION but you have $installed_kubernetes_version, consider minikube delete and retrying."
fi

# make test domain available inside cluster
if ! $KUBECTL -n kube-system get configmap coredns -oyaml | grep -qF "rewrite name regex ^.*data-hub.local\\.$ traefik.traefik.svc.cluster.local answer auto"
then
  $KUBECTL -n kube-system get configmap coredns -oyaml \
  | sed 's/^\( *\)loadbalance/\1rewrite name regex ^.*data-hub.local\\.$ traefik.traefik.svc.cluster.local answer auto\n\0/g' \
  | $KUBECTL apply -f -
  $KUBECTL rollout restart -n kube-system deployment coredns
fi

# workaround, never resolve .intra domains because they cause problems on manjaro
if ! $KUBECTL -n kube-system get configmap coredns -oyaml | grep 'template ANY ANY intra' -q
then
  $KUBECTL -n kube-system get configmap coredns -oyaml \
  | sed 's/^        forward/        template ANY ANY intra {\n           rcode NXDOMAIN\n        }\n        forward/' \
  | $KUBECTL apply -f -
fi
