#!/bin/bash

source "$(dirname "$BASH_SOURCE")/.common"

NAMESPACE="-n udh"

DATABASE_USER="${1-postgres}"
DATABASE="${2-mdb}"
if [ "$DATABASE_USER" == "postgres" ]
then
  SECRET=local-udh-platform-cnpg-superuser
else
  SECRET=local-udh-platform-$DATABASE_USER-postgres-credentials
fi
PGUSER="$(${KUBECTL} get secret $NAMESPACE $SECRET -ojsonpath="{.data.username}" | base64 -d)"
PGPASSWORD="$(${KUBECTL} get secret $NAMESPACE $SECRET -ojsonpath="{.data.password}" | base64 -d)"

exec ${KUBECTL} exec $NAMESPACE -ti local-udh-platform-cnpg-1 -- \
  env PGPASSWORD="$PGPASSWORD" psql -U $PGUSER $DATABASE -h localhost
